[general]
molecule_name = undecane
smiles = CCCCCCCCCCC
work_root = Polarizability_of_molecules_gaussian

[tools]
obabel = obabel
crest = crest
g16 = g16
# If Gaussian needs a profile sourced to set GAUSS_EXEDIR etc:
gaussian_profile =

[hardware]
cores_total = 90
mem_total_gb = 100
mem_headroom = 0.90

[resources]
auto_resources = yes
# set thermo_max_workers_cap to 0, if program should automatically decide
thermo_max_workers_cap = 30

# Choose cores/job for each stage (or set same for all)
opt_cores_per_job = 6
freq_cores_per_job = 6
polar_cores_per_job = 6
thermo_cores_per_job = 1

# Minimum memory per job by stage (GB)
opt_min_mem_gb = 3
freq_min_mem_gb = 5
polar_min_mem_gb = 3
thermo_min_mem_gb = 1

[chemistry]
charge_mult = 0 1
method = wB97XD/Def2TZVP
temps = 650,660,670,680,700,750

[crest]
use_crest = yes
# Start with fast sampling then optional refine
gff = yes
gfn2_refine = yes
ewin = 15
threads = 8
# Crest input will be the obabel xyz

[gaussian]
# Stages to run (you can turn off stages)
run_opt = yes
run_freq = yes
run_thermo = yes
run_polar = yes